package com.chaitanya.utility;

public enum VoucherStatusEnum {
	
	SAVE_AS_DRAFT(1),
	SEND_FOR_APPROVAL(2),
	REJECTED(3),
	COMPLETELY_APPROVED(4),
	PAID(5),
	FUNCTIONAL_PENDING_AT_1ST_LEVEL(11),
	FUNCTIONAL_APPROVED_AT_1ST_LEVEL(12),
	FUNCTIONAL_REJECTED_AT_1ST_LEVEL(13),
	FUNCTIONAL_PENDING_AT_2ND_LEVEL(21),
	FUNCTIONAL_APPROVED_AT_2ND_LEVEL(22),
	FUNCTIONAL_REJECTED_AT_2ND_LEVEL(23),
	FUNCTIONAL_PENDING_AT_3RD_LEVEL(31),
	FUNCTIONAL_APPROVED_AT_3RD_LEVEL(32),
	FUNCTIONAL_REJECTED_AT_3RD_LEVEL(33),
	FINANCE_PENDING_AT_1ST_LEVEL(111),
	FINANCE_APPOVED_AT_1ST_LEVEL(112),
	FINANCE_REJECTED_AT_1ST_LEVEL(113),
	FINANCE_PENDING_AT_2ND_LEVEL(121),
	FINANCE_APPOVED_AT_2ND_LEVEL(122),
	FINANCE_REJECTED_AT_2ND_LEVEL(123),
	FINANCE_PENDING_AT_3RD_LEVEL(131),
	FINANCE_APPOVED_AT_3RD_LEVEL(132),
	FINANCE_REJECTED_AT_3RD_LEVEL(133);
	
	private final int value;
    private VoucherStatusEnum(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
